### ISSUE TITLE
where is the 8x upsample module?

### ISSUE THREAD

**Issue by PengfeiGo** [openseg-group/OCNet.pytorch#65]
hello， thanks for your contribution。I read your paper that last module is 8x upsample to resize original size .But I did not find upsample in network/enery .py net
Did I miss something?

**Comment by PkuRainBow** [comment]
https://github.com/openseg-group/OCNet.pytorch/blob/679a45b8996c583817bbdde81971a47d71c7654e/utils/criterion.py#L29
